services:
  pos_app:
    build: ./POS.ConsoleApp
    container_name: pos_app
    volumes:
      - posdata:/app/data
    stdin_open: true
    tty: true

  pos_sync:
    build: ./POS.SyncService
    container_name: pos_sync
    depends_on:
      - store_api
    volumes:
      - posdata:/app/data

  store_api:
    build: ./StoreInventory.API
    container_name: store_api
    ports:
      - "5000:80"
    volumes:
      - storedata:/app/data

volumes:
  posdata:
  storedata: