services:
  pos_app:
    build:
      context: ./src
      dockerfile: POS.ConsoleApp/Dockerfile
    container_name: pos_app
    volumes:
      - posdata:/app/data
    stdin_open: true
    tty: true

  pos_sync:
    build:
      context: ./src
      dockerfile: POS.SyncService/Dockerfile
    container_name: pos_sync
    depends_on:
      - store_api
    volumes:
      - posdata:/app/data

  store_api:
    build:
      context: ./src
      dockerfile: StoreInventory.API/Dockerfile
    container_name: store_api
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - storedata:/app/data

volumes:
  posdata:
  storedata: